config/routes.rb
Mytracker::Application.routes.draw do
  

  resources :contacts
  resources :dashboards
  resources :accounts

  resources :drops

  devise_for :users
  root :to => redirect('/dashboards')
  
  resources :calls

end

app/models/drop.rb
class Drop < ActiveRecord::Base

	belongs_to :user
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_drop, only: [:show, :edit, :update, :destroy]

  # GET /drops
  # GET /drops.json
  def index
    @drops = current_user.drops
  end

  # GET /drops/1
  # GET /drops/1.json
  def show
  end

  # GET /drops/new
  def new
    @drop_accounts = load_accounts
    @drop_contacts = load_contacts
    @drop = Drop.new
  end

  # GET /drops/1/edit
  def edit
    @drop_accounts = load_accounts
    @drop_contacts = load_contacts
  end

  # POST /drops
  # POST /drops.json
  def create
    @drop = current_user.drops.new(drop_params)

    respond_to do |format|
      if @drop.save
        format.html { redirect_to drops_path, notice: 'Drop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @drop }
      else
        format.html { render action: 'new' }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drops/1
  # PATCH/PUT /drops/1.json
  def update
    respond_to do |format|
      if @drop.update(drop_params)
        format.html { redirect_to @drop, notice: 'Drop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drops/1
  # DELETE /drops/1.json
  def destroy
    @drop.destroy
    respond_to do |format|
      format.html { redirect_to drops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drop
      @drop = Drop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_params
      params.require(:drop).permit(:account, :scheduledrop, :actualdrop, :contactname, :contactaddress, :contactphone, :contactemail, :notes)
    end

    # Load the accounts into an array
    def load_accounts
        Account.all.map{|u| [ u.account_name, u.account_name ]}
    end

    # Load the contacts into an array
    def load_contacts
        Contact.all.map{|u| [ u.contact_name, u.contact_name ]}
    end
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/views/drops/_form.html.erb
<%= form_for(@drop) do |f| %>
  <% if @drop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drop.errors.count, "error") %> prohibited this drop from being saved:</h2>

      <ul>
      <% @drop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br>
    <%= f.select(:account, @drop_accounts) %>
  </div>
  <div class="field">
    <%= f.label :scheduledrop %><br>
    <%= f.datetime_select :scheduledrop %>
  </div>
  <div class="field">
    <%= f.label :time_of_day %><br>
    <%= f.select :time_of_day, options_for_select(%w[early-morning mid-morning late-morning early-afternoon mid-afternoon late-afternoon]) %><br>
  </div>
  <div class="field">
    <%= f.label :contactname %><br>
    <%= f.select(:contactname, @drop_contacts) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drops/edit.html.erb
<h1>Editing drop</h1>

<%= render 'form' %>

<%= link_to 'Show', @drop %> |
<%= link_to 'Back', drops_path %>

app/views/drops/index.html.erb
<% if user_signed_in? %>

<h4>The steps to Drop</h4>
1. Select an account to drop to (future)
2. Add account to drop
3. Create an email - default outlook
4. Map locations
5. Mark that I dropped - three things - Scheduled an appointment, Spoke with contact, left drop with someone, 
6. Enter notes 
7. Decide on next steps

<h1>Planned Drops</h1>



<table>
  <thead>
    <tr>
      <th>Generate Email</th>
      <th>Scheduledrop</th>
      <th>Account</th>
      <th>Time of Day</th>
      <th>Actualdrop</th>
      <th>Contactname</th>
      <th>Contactaddress</th>
      <th>Contactphone</th>
      <th>Contactemail</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @drops.each do |drop| %>
      <tr>
        <td><%= link_to 'Generate Email', '#' %></td>
        <td><%= drop.scheduledrop.strftime("%a %d") %></td>
        <td><%= drop.account %></td>
        <td><%= drop.time_of_day %></td>
        <td><%= drop.actualdrop %></td>
        <td><%= drop.contactname %></td>
        <td><%= drop.contactaddress %></td>
        <td><%= drop.contactphone %></td>
        <td><%= drop.contactemail %></td>
        <td><%= drop.notes %></td>
        <td><%= link_to 'Show', drop %></td>
        <td><%= link_to 'Edit', edit_drop_path(drop) %></td>
        <td><%= link_to 'Destroy', drop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drop', new_drop_path %>

<% end %>

app/views/drops/new.html.erb
<h1>New drop</h1>

<%= render 'form' %>

<%= link_to 'Back', drops_path %>

app/views/drops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @drop.account %>
</p>

<p>
  <strong>Scheduledrop:</strong>
  <%= @drop.scheduledrop %>
</p>
<p>
  <strong>Time of day:</strong>
  <%= @drop.time_of_day %>
</p>
<p>
  <strong>Actualdrop:</strong>
  <%= @drop.actualdrop %>
</p>

<p>
  <strong>Contactname:</strong>
  <%= @drop.contactname %>
</p>

<p>
  <strong>Contactaddress:</strong>
  <%= @drop.contactaddress %>
</p>

<p>
  <strong>Contactphone:</strong>
  <%= @drop.contactphone %>
</p>

<p>
  <strong>Contactemail:</strong>
  <%= @drop.contactemail %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @drop.notes %>
</p>

<%= link_to 'Edit', edit_drop_path(@drop) %> |
<%= link_to 'Back', drops_path %>