config/routes.rb
Mytracker::Application.routes.draw do
  

  resources :contacts
  resources :dashboards
  resources :accounts

  resources :drops

  devise_for :users
  root :to => redirect('/dashboards')
  
  resources :calls

end

app/models/call.rb
class Call < ActiveRecord::Base

	belongs_to :user
	#scope :calls, lambda { |date = Date.today| where(date: (date)) }
	scope :activeAtDate, lambda { |date = Date.today| where('date >= ?', date) }

end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index

    @calls = current_user.calls

    @callCountWeekly = current_user.calls.activeAtDate(5.day.ago).count
    @callCountDaily = @calls.activeAtDate().count
    @callCountWeeklyAverage = ((@calls.activeAtDate(5.day.ago).count) / 5)
    @callCountMonthlyAverage = ((@calls.activeAtDate(1.month.ago).count) / 20)
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = current_user.calls.new(call_params)
    @call.update_attribute(:date, Date.current)    #Put in the current time
    @call.update_attribute(:time, Time.zone.now)   #Put in the current date

    respond_to do |format|
      if @call.save
        format.html { redirect_to root_path, notice: 'Call was successfully created.' } 
        format.json { render action: 'show', status: :created, location: @call }
      else
        format.html { render action: 'new' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:results, :spoken, :rvm, :lvm, :date, :time)
    end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= f.label :results %><br>
    <%= f.text_field :results, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :spoken %><br>
    <%= f.check_box :spoken %>
  </div>
  <div class="field">
    <%= f.label :rvm %><br>
    <%= f.check_box :rvm %>
  </div>
  <div class="field">
    <%= f.label :lvm %><br>
    <%= f.check_box :lvm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<% if user_signed_in? %>

<h1>Listing calls</h1><br/>

<div class="row">
  <!-- Column Chart --> 

    <h3>Calls Per Day</h3>
    <%= column_chart @calls.group_by_day(:time, format: "%a %d", week_start: :mon, range: 5.day.ago.midnight..Time.now ).count %>

</div>

<%= @callCountDaily %> - Calls Today<br/>
<%= @callCountWeekly %> - Weekly Calls (Last 5 Days)<br/>
<%= @callCountWeeklyAverage %> - Average Calls per Week <br/>
<%= @callCountMonthlyAverage %> - Average Calls per Month <br/><br/>

<%= link_to new_call_path, class: 'btn btn-primary btn-lg' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Call
<% end %>
<br /><br />
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Results</th>
      <th>Spoken</th>
      <th>Rvm</th>
      <th>Lvm</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.date.strftime("%a") %></td>
        <td><%= call.time.in_time_zone('Central Time (US & Canada)').strftime("%I:%M")  %></td> 
        <td><%= call.results %></td>
        <td><%= call.spoken %></td>
        <td><%= call.rvm %></td>
        <td><%= call.lvm %></td>
        <td><%= link_to call, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-search"></span>
          Show
          <% end %>
        </td>
        <td><%= link_to edit_call_path(call), class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
          <% end %>
        </td>
        <td><%= link_to call, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
          <span class="glyphicon glyphicon-remove"></span>
          Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_call_path, class: 'btn btn-primary btn-lg' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Call
<% end %>

<% end %>

app/views/calls/new.html.erb
<h1>New call</h1>


<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p>
  <strong>Results:</strong>
  <%= @call.results %>
</p>

<p>
  <strong>Spoken:</strong>
  <%= @call.spoken %>
</p>

<p>
  <strong>Rvm:</strong>
  <%= @call.rvm %>
</p>

<p>
  <strong>Lvm:</strong>
  <%= @call.lvm %>
</p>

<p>
  <strong>Date:</strong>
  <%= @call.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @call.time %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>