config/routes.rb
Mytracker::Application.routes.draw do
  

  resources :contacts
  resources :dashboards
  resources :accounts

  resources :drops

  devise_for :users
  root :to => redirect('/dashboards')
  
  resources :calls

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	belongs_to :account
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end


  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact_accounts = load_accounts
  end

  # GET /contacts/1/edit
  def edit
    @contact_accounts = load_accounts
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:contact_name, :contact_address, :contact_phone, :contact_email, :contact_active, :account_id)
    end

    # Testing for requesting the account id in the form
    def contact_form_account_id
      params.require(:contact).permit(:account_id)
    end

    # Load the accounts into an array
    def load_accounts
        Account.all.map{|u| [ u.account_name, u.id ]}
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_address %><br>
    <%= f.text_field :contact_address %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.select(:account_id, @contact_accounts) %>
  </div>
  <div class="field">
    <%= f.label :contact_active %><br>
    <%= f.check_box :contact_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>User Id</th>
      <th>Account Id</th>
      <th>Contact name</th>
      <th>Contact address</th>
      <th>Contact phone</th>
      <th>Contact email</th>
      <th>Contact active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.user_id %></td>
        <td><%= contact.account_id %></td>
        <td><%= contact.contact_name %></td>
        <td><%= contact.contact_address %></td>
        <td><%= contact.contact_phone %></td>
        <td><%= contact.contact_email %></td>
        <td><%= contact.contact_active %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User Id:</strong>
  <%= @contact.user_id %>
</p>

<p>
  <strong>Account Id:</strong>
  <%= @contact.account_id %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @contact.contact_name %>
</p>

<p>
  <strong>Contact address:</strong>
  <%= @contact.contact_address %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @contact.contact_phone %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @contact.contact_email %>
</p>

<p>
  <strong>Contact active:</strong>
  <%= @contact.contact_active %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>